/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoee;

import java.awt.Button;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JPanel;

/**
 *
 * @author Talha Jaleel
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    
        JPanel[][] jp;
    Button buttons[][][][] = new Button[3][3][3][3];
    
       
    public NewJFrame() {
        initComponents();
         int counter=0;
        this.jp = new JPanel[3][3];
        //JFrame f=new JFrame("ULTIMATE TIC TAC TOE");
        //setSize(600,600);
        //setSize(505,540);
        //setResizable(false);
	setDefaultCloseOperation(EXIT_ON_CLOSE);
//        for(int i=0;i<3;i++)
//        {
//        for(int j=0;j<3;j++)
//        {
//        jp[i][j]=new JPanel();
//        }
//        }
        
//        for(int i=0;i<3;i++)
//        {
//        for(int j=0;j<3;j++)
//        {
//       buttons[i][j]=new Button[3][3];
//        }
//        }
        
        
        for(int i = 0; i < 3; i++)
        {
            for(int j = 0; j<3; j++)
            {
                
                jp[i][j] = new JPanel();
                jp[i][j].setLayout(new GridLayout(3,3,5,5));
                //int h = 500/3;
                //int w = 500/3;
               int w= jPanel1.getWidth()/3;
               int h= jPanel1.getHeight()/3;
                jp[i][j].setBounds(j * w, i * h , w, h);
                jp[i][j].setBackground(Color.yellow);
                jp[i][j].setBorder(BorderFactory.createMatteBorder( 5, 5, 5, 5, Color.red));
                buttons[i][j] = new Button[3][3];
                
                for(int k = 0; k<3; k++)
                {
                    for(int l = 0; l <3; l++)
                    {
                       if(i==2 && j==2)
                       {
                       counter++;
                       System.out.println(counter);
                       }
                        buttons[i][j][k][l] = new Button();
                        
                        int hh = jp[i][j].getHeight()/3;
                        int ww = jp[i][j].getWidth()/3;
                        //buttons[i][j][k][l].setBounds(i, i, i, i);
                        buttons[i][j][k][l].setPreferredSize(new Dimension(ww-5, hh-5));
                        //buttons[i][j][k][l].set//setPreferredSize(new Dimension(ww-50, hh-50));
                        jp[i][j].add(buttons[i][j][k][l]);
                        
                    }
                    
                     }
                jPanel1.add(jp[i][j]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1015, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
